SPK_NAME = nano
SPK_VERS = 4.3
SPK_REV = 
SPK_ICON = src/nano.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = divx118
DESCRIPTION = nano is a text editor for Unix-like computing systems or operating environments using a command line interface.
DESCRIPTION_GER = nano ist ein einfacher Editor, der die Bearbeitung von Dateien in einem Terminal bzw. auf der Konsole erlaubt.
RELOAD_UI = no
DISPLAY_NAME = nano
STARTABLE = no
CHANGELOG = "Update to 4.3"

HOMEPAGE   = http://www.nano-editor.org
LICENSE    = GPLv2

SERVICE_SETUP = src/service-setup.sh

include ../../mk/spksrc.spk.mk
