SPK_NAME = bash
SPK_VERS = 5.0
SPK_REV = 
SPK_ICON = src/bash.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = divx118
DESCRIPTION = Bash is the GNU Project's shell. Bash is the Bourne Again SHell. Bash is an sh-compatible shell that incorporates useful features from the Korn shell (ksh) and C shell (csh).
RELOAD_UI = no
DISPLAY_NAME = bash
STARTABLE = no
CHANGELOG = ""

HOMEPAGE   = http://www.gnu.org/software/bash/
LICENSE    = GPLv3

SERVICE_SETUP = src/service-setup.sh

include ../../mk/spksrc.spk.mk
