SPK_NAME = iperf
SPK_VERS = 3.1.3
SPK_REV =
SPK_ICON = src/iperf.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = iPerf3 is a tool for active measurements of the maximum achievable bandwidth on IP networks.
RELOAD_UI = no
DISPLAY_NAME = iperf
STARTABLE = no
CHANGELOG = ""

HOMEPAGE   = https://iperf.fr
LICENSE    = 3-clause-BSD

SERVICE_SETUP = src/service-setup.sh

include ../../mk/spksrc.spk.mk
